conda-forge/mamba-feedstock

- recipe/meta.yaml
> release 0.0.2

- recipe/meta.yaml
> release 0.0.3

- recipe/meta.yaml
Closes https://github.com/QuantStack/mamba/issues/13
> Add entrypoint

- recipe/meta.yaml
> update to 0.0.4

- recipe/meta.yaml
> update mamba to new libsolv

- .azure-pipelines/run_docker_build.sh
- README.md
- recipe/meta.yaml
> release 0.0.6

- recipe/conda_build_config.yaml
- recipe/meta.yaml
> release 0.0.7

- recipe/meta.yaml
> release 0.0.10

- recipe/meta.yaml
Checklist
* [ x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ x] Bumped the build number (if the version is unchanged)
closes #21
> lifted up conda<4.8 requirement

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_python3.8.____cpython.yaml
- .ci_support/osx_python3.8.____cpython.yaml
- .ci_support/win_python3.8.____cpython.yaml
- README.md
- recipe/meta.yaml
> release 0.1.2

- recipe/meta.yaml
> Release 0.2.3

- recipe/meta.yaml
> release 0.2.4

- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/migrations/python38.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- recipe/meta.yaml
> release 0.2.5

- recipe/meta.yaml
> release 0.2.6

- recipe/meta.yaml
> release 0.2.7

- recipe/meta.yaml
> release 0.3.1

- recipe/meta.yaml
> release 0.3.2

- recipe/meta.yaml
> release 0.3.3

- recipe/meta.yaml
- recipe/placeholder.patch
> release 0.4.0

- recipe/meta.yaml
> release 0.5.0

- recipe/meta.yaml
> release 0.5.1

- recipe/meta.yaml
> release 0.6.1

- recipe/meta.yaml
> release 0.6.3

- .ci_support/linux_64_python3.6.____73_pypy.yaml
- .ci_support/linux_64_python3.6.____cpython.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_python3.6.____73_pypy.yaml
- .ci_support/linux_ppc64le_python3.6.____cpython.yaml
- .ci_support/linux_ppc64le_python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_python3.9.____cpython.yaml
- README.md
- recipe/meta.yaml
> Release 0.6.4

- .ci_support/linux_64_python3.6.____73_pypy.yaml
- .ci_support/linux_64_python3.6.____cpython.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .ci_support/linux_aarch64_python3.6.____73_pypy.yaml
- .ci_support/linux_aarch64_python3.6.____cpython.yaml
- .ci_support/linux_aarch64_python3.7.____cpython.yaml
- .ci_support/linux_aarch64_python3.8.____cpython.yaml
- .ci_support/linux_aarch64_python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_python3.6.____73_pypy.yaml
- .ci_support/linux_ppc64le_python3.6.____cpython.yaml
- .ci_support/linux_ppc64le_python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_python3.9.____cpython.yaml
- .ci_support/osx_64_python3.6.____73_pypy.yaml
- .ci_support/osx_64_python3.6.____cpython.yaml
- .ci_support/osx_64_python3.7.____cpython.yaml
- .ci_support/osx_64_python3.8.____cpython.yaml
- .ci_support/osx_64_python3.9.____cpython.yaml
- .ci_support/win_64_python3.6.____cpython.yaml
- .ci_support/win_64_python3.7.____cpython.yaml
- .ci_support/win_64_python3.8.____cpython.yaml
- .ci_support/win_64_python3.9.____cpython.yaml
- recipe/meta.yaml
> release 0.7.3

- .ci_support/linux_64_python3.6.____73_pypy.yaml
- .ci_support/linux_64_python3.6.____cpython.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .ci_support/linux_aarch64_python3.6.____73_pypy.yaml
- .ci_support/linux_aarch64_python3.6.____cpython.yaml
- .ci_support/linux_aarch64_python3.7.____cpython.yaml
- .ci_support/linux_aarch64_python3.8.____cpython.yaml
- .ci_support/linux_aarch64_python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_python3.6.____73_pypy.yaml
- .ci_support/linux_ppc64le_python3.6.____cpython.yaml
- .ci_support/linux_ppc64le_python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_python3.9.____cpython.yaml
- .ci_support/osx_64_python3.6.____73_pypy.yaml
- .ci_support/osx_64_python3.6.____cpython.yaml
- .ci_support/osx_64_python3.7.____cpython.yaml
- .ci_support/osx_64_python3.8.____cpython.yaml
- .ci_support/osx_64_python3.9.____cpython.yaml
- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- recipe/meta.yaml
> re-add libiconv

- recipe/meta.yaml
> rebuild for ppc64le

- recipe/meta.yaml
> Test with pip check

- recipe/meta.yaml
> release mamba 0.15.0

- recipe/meta.yaml
> release 0.15.2

- .ci_support/linux_64_python3.6.____cpython.yaml
- .ci_support/linux_64_python3.7.____73_pypy.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .ci_support/linux_aarch64_python3.6.____cpython.yaml
- .ci_support/linux_aarch64_python3.7.____73_pypy.yaml
- .ci_support/linux_aarch64_python3.7.____cpython.yaml
- .ci_support/linux_aarch64_python3.8.____cpython.yaml
- .ci_support/linux_aarch64_python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_python3.6.____cpython.yaml
- .ci_support/linux_ppc64le_python3.7.____73_pypy.yaml
- .ci_support/linux_ppc64le_python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_python3.9.____cpython.yaml
- .ci_support/osx_64_python3.6.____cpython.yaml
- .ci_support/osx_64_python3.7.____73_pypy.yaml
- .ci_support/osx_64_python3.7.____cpython.yaml
- .ci_support/osx_64_python3.8.____cpython.yaml
- .ci_support/osx_64_python3.9.____cpython.yaml
- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- .ci_support/win_64_python3.6.____cpython.yaml
- .ci_support/win_64_python3.7.____cpython.yaml
- .ci_support/win_64_python3.8.____cpython.yaml
- .ci_support/win_64_python3.9.____cpython.yaml
- recipe/meta.yaml
> Release 0.16.0

- recipe/meta.yaml
> release 0.17.0

- recipe/build_mamba.sh
- recipe/meta.yaml
Checklist
This fixes an issue where no `condabin/mamba` link was created. cc @duncanmmacleod
> fix up condabin/mamba

- conda-forge.yml
- recipe/meta.yaml
> release 0.18.1

- recipe/meta.yaml
> release 0.18.2

- recipe/meta.yaml
> release 0.19.0

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- recipe/meta.yaml
> Release 0.19.1

- .azure-pipelines/azure-pipelines-win.yml
- .github/workflows/automerge.yml
- .github/workflows/webservices.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- conda-forge.yml
- recipe/meta.yaml
> Release 0.20.0

- LICENSE.txt
- recipe/meta.yaml
> Release 0.21.0

- recipe/meta.yaml
> release 0.21.1

- recipe/meta.yaml
> release mamba 0.21.2

- recipe/meta.yaml
> release mamba 0.22.1

- .azure-pipelines/azure-pipelines-win.yml
- .circleci/config.yml
- recipe/meta.yaml
> release latest mamba

- .azure-pipelines/azure-pipelines-win.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- LICENSE.txt
- build-locally.py
- recipe/meta.yaml
> Release 0.25.0

- recipe/meta.yaml
> release 0.27.0

- recipe/meta.yaml
> release 1.1.0

- recipe/2265_use_conda_pkgs_dirs_in_explicit.patch
- recipe/meta.yaml
This would really help the mambaforge release
https://github.com/mamba-org/mamba/pull/2265
Checklist
> Patch away small inconsistency in  CONDA_PKGS_DIRS

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
Checklist
As I have a hand free at the moment, I might as well do the edits
> Update meta.yaml to release 1.4.4

- recipe/meta.yaml
> Release 1.4.6

- recipe/meta.yaml
> Release 1.4.7

- recipe/meta.yaml
> Release 1.4.9

- recipe/meta.yaml
> Release 1.5.0

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- recipe/meta.yaml
> Curl 8.4.0

- README.md
- recipe/meta.yaml
- recipe/patches/0001-libmambaConfig.patch
> Release 1.5.2

- .gitignore
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- recipe/meta.yaml
> Release 2.0.0a2

- .ci_support/migrations/fmt10.yaml
- recipe/meta.yaml
> Correct libmamba version

- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- build-locally.py
- recipe/meta.yaml
> Release 2.0.0alpha3

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- azure-pipelines.yml
- recipe/meta.yaml
> Release 1.5.8

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- azure-pipelines.yml
- recipe/build_mamba.bat
- recipe/build_mamba.sh
- recipe/meta.yaml
> Release 2.0.0alpha4

- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Release 2.0.0beta1

- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- recipe/meta.yaml
> Release 2.0.0beta3

- .ci_support/linux_64_.yaml
- recipe/meta.yaml
> Release 2.0.0rc0

- .scripts/build_steps.sh
- recipe/meta.yaml
> Release 2.0.0rc1

- recipe/meta.yaml
> Release 2.0.0rc2

- recipe/meta.yaml
> Release 2.0.0rc5

- recipe/meta.yaml
> Release 2.0.0

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- README.md
- recipe/conda_build_config.yaml
- recipe/meta.yaml
Checklist
I propose that we use a dedicated branch for `mamba_dev`.
> Revert channel to conda-forge's `main` channel

- conda-forge.yml
> Perform migrations on `1.x` and `prerelease` as well

- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- azure-pipelines.yml
- recipe/meta.yaml
Checklist
See: https://github.com/mamba-org/mamba/pull/3548
> Unpin libcurl <8.10

- recipe/meta.yaml
> Release 2.0.4alpha2

- build-locally.py
- recipe/meta.yaml
> Release 2.0.4alpha3

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .scripts/run_win_build.bat
- build-locally.py
- recipe/meta.yaml
> Release 2.0.4

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/spdlog113.yaml
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- recipe/meta.yaml
> Release 2.0.5.rc0

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/spdlog113.yaml
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- recipe/meta.yaml
> Release 2.0.5

- recipe/meta.yaml
Checklist
Closes #277.
Closes #276.
> Release 1.5.12

- recipe/meta.yaml
> Release 2.0.6.rc0

- .gitignore
- recipe/meta.yaml
> Release 2.0.6.rc1

- recipe/meta.yaml
> Release 2.0.6.rc2

- .gitignore
- .scripts/build_steps.sh
- .scripts/run_win_build.bat
- conda-forge.yml
- recipe/meta.yaml
Checklist
Also test on native and emulated plateforms, like on `prerelease`.
> Release 2.0.6

- recipe/build_mamba.bat
- recipe/build_mamba.sh
- recipe/meta.yaml
Checklist
Some changes have not been ported from one branch to another.
> Synchronise `prerelease` with `main`

- recipe/meta.yaml
> Release 2.0.7.rc0

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_zstd1.5.6.yaml
- .ci_support/linux_64_zstd1.5.7.yaml
- .ci_support/linux_aarch64_zstd1.5.6.yaml
- .ci_support/linux_aarch64_zstd1.5.7.yaml
- .ci_support/linux_ppc64le_zstd1.5.6.yaml
- .ci_support/linux_ppc64le_zstd1.5.7.yaml
- .ci_support/osx_64_zstd1.5.6.yaml
- .ci_support/osx_64_zstd1.5.7.yaml
- .ci_support/osx_arm64_zstd1.5.6.yaml
- .ci_support/osx_arm64_zstd1.5.7.yaml
- .ci_support/win_64_zstd1.5.6.yaml
- .ci_support/win_64_zstd1.5.7.yaml
- README.md
- recipe/conda_build_config.yaml
- recipe/meta.yaml
Checklist
For context see: https://github.com/conda-forge/zstandard-feedstock/issues/52#issuecomment-2679063693.
> [prerelease] Add variants for zstd

- recipe/meta.yaml
> [prerelease] Rebuild identifiable variants

- .gitignore
- recipe/meta.yaml
> Release 2.0.7.rc1

- recipe/meta.yaml
> rebuild with fmt<11.1

- recipe/meta.yaml
> Release 2.0.8

- recipe/meta.yaml
Checklist
Fix https://github.com/conda-forge/mamba-feedstock/issues/304.
We can relax the specification of fmt since https://github.com/conda-forge/fmt-feedstock/pull/63/ has been merged.
> Rebuild for fmt 11.1

- .scripts/run_docker_build.sh
- build-locally.py
- recipe/meta.yaml
> Release 2.1.0

- .scripts/run_win_build.bat
- recipe/meta.yaml
Checklist
~~One thing I'm unsure is whether we should upgrade to nlohmann_json 3.12.~~
> Release 2.1.1

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- README.md
- recipe/build_mamba.sh
- recipe/recipe.yaml
> feat(dev): Add libmambapy-stubs

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/recipe.yaml
> Add libmambapy-stubs

- .ci_support/migrations/fmt112.yaml
- conda-forge.yml
- recipe/recipe.yaml
> Rebuild for fmt 11.2
